# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deck < Formula
  desc "Structured workflows for air-gapped operations."
  homepage "https://github.com/Airgap-Castaways/deck"
  version "0.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Airgap-Castaways/deck/releases/download/v0.2.3/deck_0.2.3_darwin_amd64.tar.gz"
      sha256 "12d8a2641f50f7b0e248bdb53feed2b786148f127d905035619fb06795fc6434"

      define_method(:install) do
        bin.install "deck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Airgap-Castaways/deck/releases/download/v0.2.3/deck_0.2.3_darwin_arm64.tar.gz"
      sha256 "f6272bf40101807d03647de5eea64d9fd5e451b3663cfd0a366ce7723c59ed11"

      define_method(:install) do
        bin.install "deck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Airgap-Castaways/deck/releases/download/v0.2.3/deck_0.2.3_linux_amd64.tar.gz"
      sha256 "0fec85d27de2e2c92e6ee77f002b4ad22daf756502d682aaf47beaf3acd8c5ce"
      define_method(:install) do
        bin.install "deck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Airgap-Castaways/deck/releases/download/v0.2.3/deck_0.2.3_linux_arm64.tar.gz"
      sha256 "c922a2b53adf72f98e123afdbe6d7af1bc0fc488fae3530ec0c7d483b7f50463"
      define_method(:install) do
        bin.install "deck"
      end
    end
  end

  test do
    system "#{bin}/deck", "version"
  end
end
