# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deck < Formula
  desc "Structured workflows for air-gapped operations."
  homepage "https://github.com/Airgap-Castaways/deck"
  version "0.2.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Airgap-Castaways/deck/releases/download/v0.2.4/deck_0.2.4_darwin_amd64.tar.gz"
      sha256 "0fb7889db0393714165c415382cadf2175de6bf10cadcbfd949c69f1b7ca5187"

      define_method(:install) do
        bin.install "deck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Airgap-Castaways/deck/releases/download/v0.2.4/deck_0.2.4_darwin_arm64.tar.gz"
      sha256 "5c5c966749f537f2deb045fcc6ae1b278b458183730fab85dedf24695fd210e8"

      define_method(:install) do
        bin.install "deck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Airgap-Castaways/deck/releases/download/v0.2.4/deck_0.2.4_linux_amd64.tar.gz"
      sha256 "c58f5b29cf8f23b857b499a71ccd4d1f2f7b9126c914375ce376d93298008745"
      define_method(:install) do
        bin.install "deck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Airgap-Castaways/deck/releases/download/v0.2.4/deck_0.2.4_linux_arm64.tar.gz"
      sha256 "d90d828f8a5a0c4c65d8bebd66973fcb535c7dabcc0eea66c653e2c55285f473"
      define_method(:install) do
        bin.install "deck"
      end
    end
  end

  test do
    system "#{bin}/deck", "version"
  end
end
